define("coord",[],function(){function a(b){this.y=this.x=0;this.initialize(b)}a.prototype.initialize=function(b){var a=null,d={x:0,y:0},b=b||d;for(a in d)"undefined"==typeof b[a]&&(b[a]=d[a]);for(a in b)this[a]=b[a]};a.prototype.move=function(b,a){this.x=b;this.y=a;return this};a.prototype.plus=function(b){return new a({x:this.x+b.x,y:this.y+b.y})};a.prototype.minus=function(b){return new a({x:this.x-b.x,y:this.y-b.y})};a.prototype.scale=function(b){return new a({x:this.x*b,y:this.y*b})};a.prototype.dist=
function(a){return Math.sqrt((this.x-a.x)*(this.x-a.x)+(this.y-a.y)*(this.y-a.y))};a.prototype.midpoint=function(b){return new a({x:(this.x+b.x)/2,y:(this.y+b.y)/2})};return a});define("ball",["coord"],function(a){function b(b,d,h){a.call(this,{x:b,y:d});this.r=h||0}b.prototype=new a;b.prototype.constructor=b;b.prototype.draw=function(a){a.beginPath();a.moveTo(this.x,this.y);a.arc(this.x,this.y,this.r,0,2*Math.PI,!0);a.fill()};return b});
define("hue",[],function(){function a(a,e,d,h){this.r=a||0;this.g=e||0;this.b=d||0;this.a=h||1}a.prototype.toString=function(){return"rgba("+this.r+", "+this.g+", "+this.b+", "+this.a+")"};return a});
define("path",["coord","hue"],function(a,b){function e(d){Array.call(this,d);this.topLeft=new a({x:9E3,y:9E3});this.bottomRight=new a({x:0,y:0});this.hue=new b}e.prototype=[];e.prototype.constructor=e;e.prototype.add=function(a){a.hasOwnProperty("x")&&a.hasOwnProperty("y")&&(Array.prototype.push.call(this,a),this.updateBounds(a.x,a.y))};e.prototype.isEmpty=function(){return 0===this.length};e.prototype.push=function(a){this.add(a);return this.length};e.prototype.updateBounds=function(a,h){a<this.topLeft.x?
this.topLeft.x=a:a>this.bottomRight.x&&(this.bottomRight.x=a);h<this.topLeft.y?this.topLeft.y=h:h>this.bottomRight.y&&(this.bottomRight.y=h)};e.prototype.clear=function(){this.length=0};e.prototype.last=function(){return new a({x:this[this.length-1].x,y:this[this.length-1].y})};e.prototype.fromOther=function(a){var h,w;w=new e(a.length);w.hue=new b(a.hue.r,a.hue.g,a.hue.b,a.hue.a);for(h=0;h<a.length;h++)w.push(a[h]);return w};e.prototype.draw=function(a){var h;if(this.length){a.save();a.strokeStyle=
this.hue.toString();a.beginPath();a.moveTo(this[0].x,this[0].y);for(h=1;h<this.length;h++)a.lineTo(this[h].x,this[h].y);a.stroke();a.restore()}};e.prototype.undraw=function(a){0<this.length&&a.clearRect(this.topLeft.x-1,this.topLeft.y-1,this.bottomRight.x+1-this.topLeft.x,this.bottomRight.y+1-this.topLeft.y)};return e});
define("plane",["coord","ball","path"],function(a,b,e){function d(a,d,e,r){this.vx=this.vy=this.waypoint=this.frame=0;this.path=null;this.scale=1;this.minScale=0.125;this.init(r);this.pos=new b(a.x,a.y,Math.round(Math.max(d.width,d.height)/2));this.width=d.width;this.height=d.height;this.landing=this.selected=!1;this.img=new Image;this.initMask(e,d)}d.prototype.init=function(){};d.prototype.hasPath=function(){return null!=this.path};d.prototype.getHeading=function(){return Math.atan2(this.vy,this.vx)};
d.prototype.setHeading=function(a){var b=this.velocity();this.vx=b*Math.cos(a);this.vy=b*Math.sin(a)};d.prototype.setScale=function(a){this.scale=a<=this.minScale?this.minScale:a;this.pos.r=Math.round(Math.max(this.width,this.height)/2*this.scale)};d.prototype.setPath=function(a){this.path=(new e).fromOther(a);this.waypoint=1};d.prototype.nextWaypoint=function(){this.hasPath()&&this.path.shift()};d.prototype.velocity=function(){return Math.sqrt(this.vx*this.vx+this.vy*this.vy)};d.prototype.setVelocity=
function(a){var b=this.getHeading();this.vx=a*Math.cos(b);this.vy=a*Math.sin(b)};d.prototype.dist=function(a){return this.pos.dist(a)};d.prototype.draw=function(a){a.save();a.translate(this.pos.x,this.pos.y);a.rotate(this.getHeading()+Math.PI/2);a.drawImage(this.img,-this.width*this.scale/2,-this.height*this.scale/2,this.width*this.scale,this.height*this.scale);this.selected&&(a.strokeStyle="yellow",a.beginPath(),a.arc(0,0,this.pos.r,0,2*Math.PI,!1),a.stroke());a.restore()};d.prototype.clear=function(a){a.save();
a.translate(this.pos.x,this.pos.y);a.rotate(this.heading+Math.PI/2);a.clearRect(-(this.pos.r+3),-(this.pos.r+3),2*(this.pos.r+3),2*(this.pos.r+3));a.restore()};d.prototype.initMask=function(a,b){var d=document.createElement("canvas");d.width=this.width;d.height=this.height;var e=d.getContext("2d");e.drawImage(a,0,0);for(var p=e.getImageData(0,0,this.width,this.height),t=p.data,s=t.length-1;0<s;s-=4)t[s]=255-t[s-3];e.clearRect(0,0,this.width,this.height);e.putImageData(p,0,0);e.globalCompositeOperation=
"xor";e.drawImage(b,0,0);this.img.src=d.toDataURL("image/png")};d.prototype.move=function(a){this.pos.move(a.x,a.y)};d.prototype.land=function(a){this.setPath(a);this.move(this.path[0]);this.heading=Math.atan2(a[1].y-this.pos.y,a[1].x-this.pos.x);console.log("Set heading  vx:"+this.vx+" vy:"+this.vy+" Dist(path0):"+this.dist(this.path[0]));this.landing=!0;var b=this.velocity();this.a=0.5*(-b*b/this.dist(a[1]));console.log("Lib 249: Set acceleration to "+this.a+". v: "+b+" dist:"+this.dist(a[1]))};
return d});define("action",[],function(){function a(b){this.time=0;this.planes=[];b&&a.prototype.fromJson.call(this,b)}a.prototype.fromJson=function(a){this.time=a.time;this.planes=[].concat(a.planes)};return a});
define("engine","coord ball hue path plane action".split(" "),function(a,b,e,d,h,w){return function(){var C,r,p,t;function s(){console.log("Starting run.");k.width=k.width;x.width=x.width;u=k.width;q=k.height;g.font="normal 12px sans-serif";p=H=0;t=Date.now();0==D&&(E=0);I=0;$(x).css({left:$(k).position().left+"px",top:$(k).position().top+"px"});$(k).mousedown(L).mousedown(M).mousemove(N).mouseup(O);window.requestAnimationFrame(P)}function P(f){if(1>F)g.save(),g.font="bold 30px sans-serif",f=g.measureText("LOADING...").width,
g.fillText("LOADING...",u/2-f/2,q/2),g.restore(),console.log("loadQueue",F);else if(p=f-t,g.clearRect(0,0,250,20),g.clearRect(0,q-35,150,20),y.length&&y[0].time<=p/1E3&&($.each(y[0].planes,function(f,c){Q(c.type,new a({x:c.location.x,y:c.location.y}),c.heading);console.log("plane.heading",c.heading)}),y.shift()),$.each(i,function(f,c){if(i[f])if(c.clear(g),c.landing&&0>=Math.round(c.velocity()))c.selected&&(j=null),console.log("objList.splice("+f+", 1)"),i.splice(f,1),null!=j&&j>=f&&j--,E++;else{c.landing&&
(c.setVelocity(c.velocity()+c.a),c.setScale(0.975*c.scale));var b;a:{for(b=f+1;b<i.length;b++)if(c.dist(i[b].pos)<=Math.max(c.pos.r,i[b].pos.r)&&!i[b].landing&&!c.landing){i[b].clear(g);if(c.selected||i[b].selected)j=null;null!=j&&(j>=b?j-=2:j--);console.log("objList.splice("+b+", 1)");i.splice(b,1);console.log("objList.splice("+f+", 1)");i.splice(f,1);I++;E--;b=!0;break a}b=!1}if(!b){b=c.pos.x+Math.round(c.vx);var n=c.pos.y+Math.round(c.vy);b<-c.pos.r?b=u+c.pos.r:b>u+c.pos.r&&(b=-c.pos.r);n>q+c.pos.r?
n=-c.pos.r:n<-c.pos.r&&(n=q+c.pos.r);c.move(new a({x:Math.round(b),y:Math.round(n)}));g.fillStyle="#FF0000";!c.hasPath()&&l.length&&c.dist(l[0])<=c.pos.r&&c.setPath(l);c.hasPath()&&(b=c.waypoint,c.path.undraw(g),c.path.draw(g),b>=c.path.length?(console.log("waypoint",b,"obj.path.length",c.path.length),console.log("Path complete (obj)."),c.path.undraw(g),c.path=null,$.each(G,function(a,b){c.dist(b[0])<=c.pos.r&&c.land(b)})):(n=Math.atan2(c.path[b].y-c.pos.y,c.path[b].x-c.pos.x),console.log("Adjusting heading to "+
180*n/Math.PI+"deg."),c.setHeading(n),c.dist(c.path[b])<=0.75*c.pos.r&&c.nextWaypoint()))}}}),l.length&&l.draw(g),$.each(i,function(a,b){b.draw(g)}),H++,g.fillText("Framerate: "+Math.round(H/(p/1E3))+"    Time:"+p/1E3,5,10),g.fillText("Score: "+E+"\r\nCollisions: "+I,5,q-25),0==i.length&&0==y.length){console.log("Ending game loop.");l.length=0;$(k).off("mousedown",L).off("mousedown",M).off("mousemove",N).off("mouseup",O);var f=$("#btnStart"),b=$("#btnScore");null==f&&(f=$('<button id="btnHome"></button>'),
$("body").append(f));null==b&&(b=$('<button id="btnNext"></button>'),$("body").append(b));f.show();f.text("HOME");b.show();b.text("NEXT LEVEL");f.css({position:"absolute",top:0.75*$(k).height()+"px",left:0.33*$(k).width()+"px","z-index":"3"});b.css({position:"absolute",top:f.css("top"),left:0.33*$(k).width()+100+"px","z-index":"3"});f.one("click",J);b.one("click",R)}else window.requestAnimationFrame(P)}function S(){var a=$("#btnStart"),b=$("#btnScore");a.length||(a=$('<button id="btnStart"></button>').text("START"),
$("body").append(a));b.length||(b=$('<button id="btnScore"></button>').text("SCORES"),$("body").append(b));a.show();b.show();$("#scoreTable").length&&$("#scoreTable").hide();k.width=k.width;x.width=x.width;g.font="bold 50px Courier";g.fillStyle="rgb(163, 188, 227)";g.fillText("AIRPLANE!",250,40);a.css({position:"absolute",top:0.75*$(k).height()+"px",left:0.33*$(k).width()+"px","z-index":"3"});b.css({position:"absolute",top:a.css("top"),left:0.33*$(k).width()+100+"px","z-index":"3"});a.one("click",
T);b.one("click",U)}function V(f){$.ajax(f,{async:!1,dataType:"json",success:function(f){for(var e=G.length=0;e<f.runways.length;e+=2){var c=new d;c.add(new a({x:f.runways[e].x,y:f.runways[e].y}));c.add(new a({x:f.runways[e+1].x,y:f.runways[e+1].y}));G.push(c)}$.each(f.events,function(a,b){y.push(new w(b))});z.src="";z.src=f.bg;$(z).one("load",function(){console.log("BG loaded");m.fillStyle="#0000EE";m.fillRect(0,0,u,q);m.save();var a=z.width/2,c=z.height/2;m.drawImage(z,(u-a)/2,(q-c)/2,Math.round(a),
Math.round(c));m.restore();m.font="normal 9px sans-serif";$.each(G,function(a,c){m.fillStyle="#00FF00";(new b(c[0].x,c[0].y,3)).draw(m);m.fillStyle="#FF0000";(new b(c[1].x,c[1].y,3)).draw(m)})})}})}function L(){}function M(b){K=!0;var n=new a({x:b.offsetX,y:b.offsetY});j=null;$.each(i,function(b,c){if(c instanceof h&&(c.selected=c.pos.dist(n)<=c.pos.r+3))j=b,c.hasPath()?(c.path.undraw(g),c.path.clear()):(c.path=new d,c.path.hue=new e(A(0,255),A(0,255),A(0,255))),c.path.add(new a({x:c.pos.x,y:c.pos.y})),
c.waypoint=0});null==j&&(l.undraw(g),l.clear(),l.add(new a({x:b.offsetX,y:b.offsetY})));C=Date.now();r=0}function N(b){r=Date.now()-C;K&&6<r&&(b=new a({x:b.offsetX,y:b.offsetY}),null==j?5<l.last().dist(b)&&l.add(b):i[j].hasPath()&&5<i[j].path.last().dist(b)&&i[j].path.push(b),C=Date.now(),r=0)}function O(b){K=!1;C=Date.now();r=0;null!=j&&i[j].hasPath()?(i[j].path.add(new a({x:b.offsetX,y:b.offsetY})),i[j].selected=!1):l.push(new a({x:b.offsetX,y:b.offsetY}))}function T(){console.log("startClick");
var a=$("#btnStart"),b=$("#btnScore");a.hide();b.hide();D=0;V(o[D]);b.off("click",U);s()}function U(){console.log("scoreClick");var a=$("#btnStart");$("#btnScore").hide();a.text("HOME");a.off("click",T);a.one("click",J);var b,d,c;$.getJSON("json/scores.json",function(a){b=$("#scoreTable");b.length?b.empty():(b=$('<table id="scoreTable"></table>'),$("body").append(b));d=$("<tr></tr>").append("<th>Name</th>").append("<th>Date</th>").append("<th>Level</th>").append("<th>Score</th>");b.append(d);$.each(a.scores,
function(a,f){c=$("<tr></tr>").append("<td>"+f.name+"</td>").append("<td>"+f.date+"</td>").append("<td>"+f.level+"</td>").append("<td>"+f.score+"</td>");b.append(c)});b.css({position:"absolute",top:0.35*$(k).height()+"px",left:0.25*$(k).width()+"px","z-index":"2"});b.show()})}function J(){console.log("homeClick");var a=$("#btnStart"),b=$("#btnScore");a.text("START");b.text("SCORES");b.off("click",R);S()}function R(){console.log("nextClick");var a=$("#btnStart"),b=$("#btnScore");D<o.length-1&&(a.off("click",
J),a.hide(),b.hide(),V(o[++D]),s())}function Q(b,d,e){null==b&&(b=A(0,v.length));d||(d=new a({x:A(0,u),y:A(0,q)}));null==e&&(e=Math.random()*(2*Math.PI-0)+0);try{var c=new h(d,v[b].img,v[b].alpha)}catch(g){console.log(v);console.log(g);return}c.setScale(0.25);switch(b){case 1:c.setVelocity(6);break;case 2:c.setVelocity(4);break;case 0:c.setVelocity(8)}c.setHeading(e);i.push(c)}function B(a){var b=new Image;F--;$(b).one("load",W);b.src=a;return b}function W(){F++;console.log("Resource loaded:",this,
"complete: ",this.complete)}function A(a,b){return Math.floor(Math.random()*(b-a+1))+a}var g,m,u,q,H=0,E=0,I=0,j=null,D=0,F=1,K=!1,l=new d;r=C=t=p=void 0;var z=new Image,k=$("#cvsFront")[0],x=$("#cvsBg")[0],i=[],o=[],v=[],y=[],G=[];g=k.getContext("2d");g.font="normal 12px sans-serif";m=x.getContext("2d");l.hue=new e(0,170,0);v.push({img:B("img/Leer.jpg"),alpha:B("img/Leer.jpg")});v.push({img:B("img/AirlinerClr.jpg"),alpha:B("img/Airliner.jpg")});v.push({img:B("img/CessnaClr.jpg"),alpha:B("img/Cessna.jpg")});
o.push("json/lvl1.json");o.push("json/lvl2.json");o.push("json/lvl3.json");o.push("json/lvl4.json");o.push("json/lvl5.json");o.push("json/lvl6.json");o.push("json/lvl7.json");$("btnAdd").click(function(){Q()});return{home:S}}});