define("coord",[],function(){function b(a){this.y=this.x=0;this.initialize(a)}b.prototype.initialize=function(a){var e=null,i={x:0,y:0},a=a||i;for(e in i)"undefined"==typeof a[e]&&(a[e]=i[e]);for(e in a)this[e]=a[e]};b.prototype.move=function(a,e){this.x=a;this.y=e;return this};b.prototype.plus=function(a){return new b({x:this.x+a.x,y:this.y+a.y})};b.prototype.minus=function(a){return new b({x:this.x-a.x,y:this.y-a.y})};b.prototype.scale=function(a){return new b({x:this.x*a,y:this.y*a})};b.prototype.dist=
function(a){return Math.sqrt((this.x-a.x)*(this.x-a.x)+(this.y-a.y)*(this.y-a.y))};b.prototype.midpoint=function(a){return new b({x:(this.x+a.x)/2,y:(this.y+a.y)/2})};return b});define("ball",["coord"],function(b){function a(a,i,d){b.call(this,{x:a,y:i});this.r=d||0}a.prototype=new b;a.prototype.constructor=a;a.prototype.draw=function(a){a.beginPath();a.moveTo(this.x,this.y);a.arc(this.x,this.y,this.r,0,2*Math.PI,!0);a.fill()};return a});
define("hue",[],function(){function b(a,b,i,d){this.r=a||0;this.g=b||0;this.b=i||0;this.a=d||1}b.prototype.toString=function(){return"rgba("+this.r+", "+this.g+", "+this.b+", "+this.a+")"};return b});
define("path",["coord","hue"],function(b,a){function e(i){Array.call(this,i);this.topLeft=new b({x:9E3,y:9E3});this.bottomRight=new b({x:0,y:0});this.hue=new a}e.prototype=[];e.prototype.constructor=e;e.prototype.add=function(a){a.hasOwnProperty("x")&&a.hasOwnProperty("y")&&(Array.prototype.push.call(this,a),this.updateBounds(a.x,a.y))};e.prototype.isEmpty=function(){return 0===this.length};e.prototype.push=function(a){this.add(a);return this.length};e.prototype.updateBounds=function(a,b){a<this.topLeft.x?
this.topLeft.x=a:a>this.bottomRight.x&&(this.bottomRight.x=a);b<this.topLeft.y?this.topLeft.y=b:b>this.bottomRight.y&&(this.bottomRight.y=b)};e.prototype.clear=function(){this.length=0};e.prototype.last=function(){return new b({x:this[this.length-1].x,y:this[this.length-1].y})};e.prototype.fromOther=function(b){var d,x;x=new e(b.length);x.hue=new a(b.hue.r,b.hue.g,b.hue.b,b.hue.a);for(d=0;d<b.length;d++)x.push(b[d]);return x};e.prototype.draw=function(a){var b;if(this.length){a.save();a.strokeStyle=
this.hue.toString();a.beginPath();a.moveTo(this[0].x,this[0].y);for(b=1;b<this.length;b++)a.lineTo(this[b].x,this[b].y);a.stroke();a.restore()}};e.prototype.undraw=function(a){0<this.length&&a.clearRect(this.topLeft.x-1,this.topLeft.y-1,this.bottomRight.x+1-this.topLeft.x,this.bottomRight.y+1-this.topLeft.y)};return e});
define("animation",[],function(){function b(a){this.fps=this.repeat=this.length=this.firstFrame=0;this.init(a)}b.prototype.init=function(a){var b=null,i={firstFrame:0,length:0,repeat:0,fps:60},a=a||i;for(b in i)"undefined"==typeof a[b]&&(a[b]=i[b]);for(b in a)this[b]=a[b]};return b});
define("plane",["coord","ball","path","animation"],function(b,a,e,i){function d(b,d,e,n,t,r){this.vx=this.vy=this.waypoint=this.frame=0;this.path=null;this.scale=1;this.minScale=0.125;this.init(r);this.pos=new a(b.x,b.y,Math.round(Math.max(n,t)/2));this.width=n;this.height=t;this.landing=this.selected=!1;this.img=new Image;this.initMask(e,d);this.animations={};this.animations.crash=new i({firstFrame:1,length:1,repeat:6});this.animations.flight=new i({firstFrame:1,length:1,repeat:-1});this.setAnim(this.animations.flight);
this.frameY=this.frameX=0;this.cols=Math.floor(d.width/n);this.rows=Math.floor(d.height/t);this.fCount=0;this.dead=this.crashing=!1}d.prototype.init=function(){};d.prototype.hasPath=function(){return null!=this.path};d.prototype.getHeading=function(){return Math.atan2(this.vy,this.vx)};d.prototype.setAnim=function(a){this.curAnimation=a;this.frame=this.curAnimation.firstFrame;this.loop=a.repeat};d.prototype.setHeading=function(a){var b=this.velocity();this.vx=b*Math.cos(a);this.vy=b*Math.sin(a)};
d.prototype.setScale=function(a){this.scale=a<=this.minScale?this.minScale:a;this.pos.r=Math.round(Math.max(this.width,this.height)/2*this.scale)};d.prototype.setPath=function(a){this.path=(new e).fromOther(a);this.waypoint=1};d.prototype.nextWaypoint=function(){this.hasPath()&&this.path.shift()};d.prototype.velocity=function(){return Math.sqrt(this.vx*this.vx+this.vy*this.vy)};d.prototype.setVelocity=function(a){var b=this.getHeading();this.vx=a*Math.cos(b);this.vy=a*Math.sin(b)};d.prototype.updateFrame=
function(){this.frameX=(this.frame-1)*this.width-Math.floor((this.frame-1)/this.cols)*this.cols*this.width;this.frameY=Math.floor((this.frame-1)/this.cols)*this.height};d.prototype.dist=function(a){return this.pos.dist(a)};d.prototype.draw=function(a){this.updateFrame();this.fCount++;a.save();a.translate(this.pos.x,this.pos.y);a.rotate(this.getHeading()+Math.PI/2);a.drawImage(this.img,this.frameX,this.frameY,this.width,this.height,-this.width*this.scale/2,-this.height*this.scale/2,this.width*this.scale,
this.height*this.scale);console.log("frame",this.frame,"frameX",this.frameX,"frameY",this.frameY);this.selected&&(a.strokeStyle="yellow",a.beginPath(),a.arc(0,0,this.pos.r,0,2*Math.PI,!1),a.stroke());a.restore();this.frame+1>this.curAnimation.firstFrame+this.curAnimation.length-1?(console.log("End of current animation loop"),this.frame=this.curAnimation.firstFrame,-1===this.curAnimation.repeat?this.frame=this.curAnimation.firstFrame:0<this.loop&&this.loop--,this.crashing?(console.log("Setting plane to DEAD"),
this.dead=!0):this.fCount=0):this.fCount>=60/this.curAnimation.fps&&(this.frame++,this.fCount=0)};d.prototype.clear=function(a){a.save();a.translate(this.pos.x,this.pos.y);a.rotate(this.heading+Math.PI/2);a.clearRect(-(this.pos.r+3),-(this.pos.r+3),2*(this.pos.r+3),2*(this.pos.r+3));a.restore()};d.prototype.crash=function(){console.log("Beginning crash sequence");this.crashing=!0;this.setAnim(this.animations.crash);console.log("Animation set to",this.curAnimation);this.fCount=0;this.updateFrame()};
d.prototype.initMask=function(a,b){var d=document.createElement("canvas");d.width=b.width;d.height=b.height;var e=d.getContext("2d");e.drawImage(a,0,0);for(var i=e.getImageData(0,0,b.width,b.height),r=i.data,s=r.length-1;0<s;s-=4)r[s]=255-r[s-3];e.clearRect(0,0,b.width,b.height);e.putImageData(i,0,0);e.globalCompositeOperation="xor";e.drawImage(b,0,0);this.img.src=d.toDataURL("image/png")};d.prototype.move=function(a){this.pos.move(a.x,a.y)};d.prototype.land=function(a){this.setPath(a);this.move(this.path[0]);
this.heading=Math.atan2(a[1].y-this.pos.y,a[1].x-this.pos.x);console.log("Set heading  vx:"+this.vx+" vy:"+this.vy+" Dist(path0):"+this.dist(this.path[0]));this.landing=!0;var b=this.velocity();this.a=0.5*(-b*b/this.dist(a[1]));console.log("Lib 249: Set acceleration to "+this.a+". v: "+b+" dist:"+this.dist(a[1]))};return d});
define("action",[],function(){function b(a){this.time=0;this.planes=[];a&&b.prototype.fromJson.call(this,a)}b.prototype.fromJson=function(a){this.time=a.time;this.planes=[].concat(a.planes)};return b});
define("engine","coord ball hue path plane action".split(" "),function(b,a,e,i,d,x){return function(){var C,y,n,t;function r(){console.log("Starting run.");k.width=k.width;z.width=z.width;u=k.width;q=k.height;g.font="normal 12px sans-serif";n=H=0;t=Date.now();0==D&&(E=0);I=0;$(z).css({left:$(k).position().left+"px",top:$(k).position().top+"px"});$(k).mousedown(L).mousedown(M).mousemove(N).mouseup(O);console.log("about to gameTick");window.requestAnimationFrame(s)}function s(){if(1>F){g.save();g.font=
"bold 30px sans-serif";var a=g.measureText("LOADING...").width;g.fillText("LOADING...",u/2-a/2,q/2);g.restore();console.log("loadQueue",F)}else if(n=Date.now()-t,g.clearRect(0,0,250,20),g.clearRect(0,q-35,150,20),v.length&&(console.log(v[0].time,n/1E3),v[0].time<=n/1E3&&($.each(v[0].planes,function(a,c){console.log("adding plane");P(c.type,new b({x:c.location.x,y:c.location.y}),c.heading);console.log("plane.heading",c.heading)}),v.shift())),$.each(j,function(a,c){if(j[a])if(c.clear(g),console.log("obj.dead",
c.dead),c.dead)c.selected&&(h=null),console.log("objList.splice("+a+", 1)"),j.splice(a,1),null!=h&&h>=a&&h--;else if(c.landing&&0>=Math.round(c.velocity()))c.selected&&(h=null),console.log("objList.splice("+a+", 1)"),j.splice(a,1),null!=h&&h>=a&&h--,E++;else{c.landing&&(c.setVelocity(c.velocity()+c.a),c.setScale(0.975*c.scale));var f;a:{for(f=a+1;f<j.length;f++)if(c.dist(j[f].pos)<=Math.max(c.pos.r,j[f].pos.r)&&!j[f].landing&&!c.landing&&!j[f].crashing&&!c.crashing){j[f].clear(g);if(c.selected||j[f].selected)h=
null;null!=h&&(h>=f?h-=2:h--);c.crash();j[f].crash();I++;E--;f=!0;break a}f=!1}if(!f){f=c.pos.x+Math.round(c.vx);var l=c.pos.y+Math.round(c.vy);f<-c.pos.r?f=u+c.pos.r:f>u+c.pos.r&&(f=-c.pos.r);l>q+c.pos.r?l=-c.pos.r:l<-c.pos.r&&(l=q+c.pos.r);c.move(new b({x:Math.round(f),y:Math.round(l)}));g.fillStyle="#FF0000";!c.hasPath()&&m.length&&c.dist(m[0])<=c.pos.r&&c.setPath(m);c.hasPath()&&(f=c.waypoint,c.path.undraw(g),c.path.draw(g),f>=c.path.length?(console.log("waypoint",f,"obj.path.length",c.path.length),
console.log("Path complete (obj)."),c.path.undraw(g),c.path=null,$.each(G,function(a,b){c.dist(b[0])<=c.pos.r&&c.land(b)})):(l=Math.atan2(c.path[f].y-c.pos.y,c.path[f].x-c.pos.x),console.log("Adjusting heading to "+180*l/Math.PI+"deg."),c.setHeading(l),c.dist(c.path[f])<=0.75*c.pos.r&&c.nextWaypoint()))}}}),m.length&&m.draw(g),$.each(j,function(a,c){c.draw(g)}),H++,g.fillText("Framerate: "+Math.round(H/(n/1E3))+"    Time:"+n/1E3,5,10),g.fillText("Score: "+E+"\r\nCollisions: "+I,5,q-25),0==j.length&&
0==v.length){console.log("Ending game loop.");m.length=0;$(k).off("mousedown",L).off("mousedown",M).off("mousemove",N).off("mouseup",O);var a=$("#btnStart"),l=$("#btnScore");null==a&&(a=$('<button id="btnHome"></button>'),$("body").append(a));null==l&&(l=$('<button id="btnNext"></button>'),$("body").append(l));a.show();a.text("HOME");l.show();l.text("NEXT LEVEL");a.css({position:"absolute",top:0.75*$(k).height()+"px",left:0.33*$(k).width()+"px","z-index":"3"});l.css({position:"absolute",top:a.css("top"),
left:0.33*$(k).width()+100+"px","z-index":"3"});a.one("click",J);l.one("click",Q)}else window.requestAnimationFrame(s)}function R(){var a=$("#btnStart"),b=$("#btnScore");a.length||(a=$('<button id="btnStart"></button>').text("START"),$("body").append(a));b.length||(b=$('<button id="btnScore"></button>').text("SCORES"),$("body").append(b));a.show();b.show();$("#scoreTable").length&&$("#scoreTable").hide();k.width=k.width;z.width=z.width;g.font="bold 50px Courier";g.fillStyle="rgb(163, 188, 227)";g.fillText("AIRPLANE!",
250,40);a.css({position:"absolute",top:0.75*$(k).height()+"px",left:0.33*$(k).width()+"px","z-index":"3"});b.css({position:"absolute",top:a.css("top"),left:0.33*$(k).width()+100+"px","z-index":"3"});a.one("click",S);b.one("click",T)}function U(f){$.ajax(f,{async:!1,dataType:"json",success:function(f){for(var d=G.length=0;d<f.runways.length;d+=2){var c=new i;c.add(new b({x:f.runways[d].x,y:f.runways[d].y}));c.add(new b({x:f.runways[d+1].x,y:f.runways[d+1].y}));G.push(c)}$.each(f.events,function(a,
b){console.log("Adding event",b);v.push(new x(b))});A.src="";A.src=f.bg;$(A).one("load",function(){console.log("BG loaded2");o.fillStyle="#0000EE";o.fillRect(0,0,u,q);o.save();var b=A.width/2,c=A.height/2;o.drawImage(A,(u-b)/2,(q-c)/2,Math.round(b),Math.round(c));o.restore();o.font="normal 9px sans-serif";$.each(G,function(b,c){o.fillStyle="#00FF00";(new a(c[0].x,c[0].y,3)).draw(o);o.fillStyle="#FF0000";(new a(c[1].x,c[1].y,3)).draw(o)})})}})}function L(){}function M(a){K=!0;var l=new b({x:a.offsetX,
y:a.offsetY});h=null;$.each(j,function(a,c){if(c instanceof d&&(c.selected=c.pos.dist(l)<=c.pos.r+3))h=a,c.hasPath()?(c.path.undraw(g),c.path.clear()):(c.path=new i,c.path.hue=new e(B(0,255),B(0,255),B(0,255))),c.path.add(new b({x:c.pos.x,y:c.pos.y})),c.waypoint=0});null==h&&(m.undraw(g),m.clear(),m.add(new b({x:a.offsetX,y:a.offsetY})));C=Date.now();y=0}function N(a){y=Date.now()-C;K&&6<y&&(a=new b({x:a.offsetX,y:a.offsetY}),null==h?5<m.last().dist(a)&&m.add(a):j[h].hasPath()&&5<j[h].path.last().dist(a)&&
j[h].path.push(a),C=Date.now(),y=0)}function O(a){K=!1;C=Date.now();y=0;null!=h&&j[h].hasPath()?(j[h].path.add(new b({x:a.offsetX,y:a.offsetY})),j[h].selected=!1):m.push(new b({x:a.offsetX,y:a.offsetY}))}function S(){console.log("startClick");var a=$("#btnStart"),b=$("#btnScore");a.hide();b.hide();D=0;U(p[D]);b.off("click",T);r()}function T(){console.log("scoreClick");var a=$("#btnStart");$("#btnScore").hide();a.text("HOME");a.off("click",S);a.one("click",J);var b,d,c;$.getJSON("json/scores.json",
function(a){b=$("#scoreTable");b.length?b.empty():(b=$('<table id="scoreTable"></table>'),$("body").append(b));d=$("<tr></tr>").append("<th>Name</th>").append("<th>Date</th>").append("<th>Level</th>").append("<th>Score</th>");b.append(d);$.each(a.scores,function(a,f){c=$("<tr></tr>").append("<td>"+f.name+"</td>").append("<td>"+f.date+"</td>").append("<td>"+f.level+"</td>").append("<td>"+f.score+"</td>");b.append(c)});b.css({position:"absolute",top:0.35*$(k).height()+"px",left:0.25*$(k).width()+"px",
"z-index":"2"});b.show()})}function J(){console.log("homeClick");var a=$("#btnStart"),b=$("#btnScore");a.text("START");b.text("SCORES");b.off("click",Q);R()}function Q(){console.log("nextClick");var a=$("#btnStart"),b=$("#btnScore");D<p.length-1&&(a.off("click",J),a.hide(),b.hide(),U(p[++D]),r())}function P(a,e,g){null==a&&(a=B(0,w.length));e||(e=new b({x:B(0,u),y:B(0,q)}));null==g&&(g=Math.random()*(2*Math.PI-0)+0);try{var c=new d(e,w[a].img,w[a].alpha,w[a].frameWidth,w[a].frameHeight);console.log(c.animations.flight);
1==a&&(c.animations.flight.firstFrame=1,c.animations.flight.length=8,c.animations.flight.repeat=-1,c.animations.flight.fps=15,c.animations.crash.firstFrame=9,c.animations.crash.length=8,c.animations.crash.repeat=1,c.animations.crash.fps=15)}catch(h){console.log(w);console.log(h);return}c.setScale(0.25);switch(a){case 1:c.setVelocity(6);break;case 2:c.setVelocity(4);break;case 0:c.setVelocity(8)}c.setHeading(g);console.log("Heading set to",g);j.push(c)}function V(a){var b=new Image;F--;$(b).one("load",
W);b.src=a;return b}function W(){F++;console.log("Resource loaded:",this,"complete: ",this.complete)}function B(a,b){return Math.floor(Math.random()*(b-a+1))+a}var g,o,u,q,H=0,E=0,I=0,h=null,D=0,F=1,K=!1,m=new i;y=C=t=n=void 0;var A=new Image,k=$("#cvsFront")[0],z=$("#cvsBg")[0],j=[],p=[],w=[],v=[],G=[];g=k.getContext("2d");g.font="normal 12px sans-serif";o=z.getContext("2d");m.hue=new e(0,170,0);$.ajax("json/planes.json",{async:!1,dataType:"json",success:function(a){$.each(a.planes,function(a,b){console.log("Adding plane",
b);w.push({img:V(b.img),alpha:V(b.alpha),frameWidth:b.frameWidth,frameHeight:b.frameHeight})})}});p.push("json/lvl1.json");p.push("json/lvl2.json");p.push("json/lvl3.json");p.push("json/lvl4.json");p.push("json/lvl5.json");p.push("json/lvl6.json");p.push("json/lvl7.json");$("btnAdd").click(function(){P()});return{home:R}}});